#!/usr/bin/env python

if __name__ == "__main__":

   from minion.frontend import app, db

   db.create_all()

   app.secret_key = "baconcheesebaconcheese"
   app.run(host='0.0.0.0', port=8080, debug=True)
