#!/usr/bin/env python


import optparse

from minion.frontend import app


if __name__ == "__main__":

   parser = optparse.OptionParser()
   parser.add_option("-d", "--debug", default=False, action="store_true")
   parser.add_option("-a", "--address", default="127.0.0.1")
   parser.add_option("-p", "--port", type="int", default=8080)

   (options, args) = parser.parse_args()

   if options.debug:
      app.debug=True

   app.run(host=options.address, port=options.port)
